language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev $PREFER_LOWEST
  - travis_retry phpenv rehash

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
